language: php

notifications:
  email:
    on_success: never

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip

jobs:
  include:

    -   name: 'PHPUnit with PHP 7.2'
        php: 7.2
        before_script: composer install -n
        script: vendor/bin/phpunit --testsuite small

    -   name: 'PHPUnit with PHP 7.3'
        php: 7.3
        before_script: composer install -n
        script: vendor/bin/phpunit --testsuite small

    -   name: 'PHPUnit with PHP 7.4'
        php: 7.4
        before_script: composer install -n
        script: vendor/bin/phpunit --testsuite small

    -   name: 'PHPUnit with lowest dependencies'
        php: 7.2
        before_script: composer update --prefer-lowest --prefer-stable -n
        script: vendor/bin/phpunit --testsuite small
        env:
          DEPLOY_JOB: true

#    -   name: 'Runtime tests'
#        php: 7.3
#        before_script:
#          - composer install -n
#          - pip install --user awscli
#          - pip install --user aws-sam-cli
#        script: travis_retry vendor/bin/phpunit --testsuite runtimes
#        # This job is testing the runtimes that are published online, it doesn't make sense to run it on
#        # pull requests and branches, it's more a watchdog than a CI job
#        if: branch = master AND fork = false

    -   name: 'PHPStan'
        php: 7.3
        before_script: composer install -n
        script: vendor/bin/phpstan analyse

before_deploy:
  - cd runtime
  - DOCKER_BUILD_FLAGS="--quiet" travis_wait 90  make docker-images
  - cd ..

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && DOCKER_BUILD_FLAGS="--quiet" make docker-images
  skip_cleanup: true
  on:
    repo: brefphp/bref
    tags: true
    all_branches: true
    condition: $DEPLOY_JOB = true