service: bref-demo

provider:
    name: aws
    runtime: provided.al2
    region: us-east-2
    logs:
        restApi: true
    apiGateway:
        binaryMediaTypes:
            - '*/*'

plugins:
    - ./index.js

package:
    patterns:
        - '!**'
        - 'demo/**'
        - 'src/**'
        - 'vendor/**'

functions:
    function:
        handler: demo/function.php
        description: 'Bref CLI demo'
        layers:
            - ${bref:layer.php-74}
        environment:
            BREF_LOOP_MAX: 100

    http:
        handler: demo/http.php
        description: 'Bref HTTP demo'
        timeout: 5 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            -   http: 'ANY /'

    psr7:
        handler: demo/psr7.php
        description: 'Bref HTTP demo with a PSR-7 handler'
        timeout: 5 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74}
        events:
            -   http: 'ANY /psr7'
            -   httpApi: 'GET /psr7'
        environment:
            BREF_LOOP_MAX: 100

    http-api:
        handler: demo/http.php
        description: 'Bref HTTP demo'
        timeout: 5 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            -   httpApi: '*'

    console:
        handler: demo/console.php
        description: 'Bref console command demo'
        timeout: 900
        layers:
            - ${bref:layer.php-74}
            - ${bref:layer.console}
