version: '3.8'

services:
  publish:
    image: amazon/aws-cli
    entrypoint: /bin/bash
    command: /publish.sh
    environment: [REGION, AWS_PROFILE, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN, LAYER_NAME, AWS_STS_REGIONAL_ENDPOINTS]
    volumes: [./publish.sh:/publish.sh, ~/.aws:/root/.aws, /tmp/bref-zip/:/tmp/bref-zip/]
